version: "3.5"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    networks:
      - backend

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    links:
      - elasticsearch
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - backend

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    links:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - ./filebeat/data:/usr/share/filebeat/data:rw
      - ./logs:/tmp:rw
    depends_on:
      - logstash
    networks:
      - backend

  loganalyticsservice:
    build: ./LogAnalyticsService
    links:
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - backend
      - frontend

  loganalyticsui:
    build:
      context: ./log-analytics-dashboard
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "3000:80"
    restart: on-failure
    depends_on:
      - loganalyticsservice
    networks:
      - frontend

networks:
  backend:
  frontend:
